// Code generated by "stringer -type=Type"; DO NOT EDIT.

package command

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Select-1]
	_ = x[Create-2]
	_ = x[Insert-3]
	_ = x[Drop-4]
}

const _Type_name = "UnknownSelectCreateInsertDrop"

var _Type_index = [...]uint8{0, 7, 13, 19, 25, 29}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
